# B"H


In [6]:
import numpy as np

## Dot Product and Vector Addition

### Dot Product

When multiplying **vectors**, you either perform a **dot product** or a **cross product**. 

A **cross product** results in a **vector** while a **dot product** results in a **scalar** (a single value/number).

<br><br>

---

Dot product of two vectors:

![](https://drive.google.com/uc?id=1QrMzksXFeQvkCO5ksHXm7N6kwoj1xcIf)

In [1]:
a = [1, 2, 3]
b = [2, 3, 4]

In [2]:
dot_product = (a[0]*b[0]) + (a[1]*b[1]) + (a[2]*b[2])

In [10]:
dot_product

20

<br><br>

---

### Dot Product using Numpy

In [11]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

In [12]:
dot_product = np.dot(weights, inputs)
dot_product

2.8

In [13]:
output = dot_product + bias
output

4.8

### Vector Addition

---

The **addition** of the two **vectors** is an operation performed **element-wise**, which means that both vectors have to be of the same size, and the result will become a vector of this size as well.

![](https://drive.google.com/uc?id=1eZ-KV1T62fJci_7een4iqcBliuNOlsmG)

In [7]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

In [9]:
added_vectors = a + b

added_vectors

array([3, 5, 7])

## A Layer of Neurons with NumPy

Let's calculate the output of a layer of 3 neurons, which means the weights will be a matrix or list of weight vectors.

NumPy makes this very easy for us - treating this **matrix** as a list of vectors and performing the dot product **one by one** with the vector
of inputs, returning a list of dot products.

![](https://drive.google.com/uc?id=1XkPRjVG7hjyWVwpC1l0yAjTS-kW_-pw8)

In [14]:
inputs = [1.0, 2.0, 3.0, 2.5]

In [15]:
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]


In [16]:
biases = [2.0, 3.0, 0.5]

In [17]:
dot_product = np.dot(weights, inputs)
dot_product

array([ 2.8  , -1.79 ,  1.885])

In [18]:
output = dot_product + biases
output 

array([4.8  , 1.21 , 2.385])

## A Batch of Data

To train, neural networks tend to receive data in **batches**.

In [20]:
inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2.0, 3.0, 0.5]

We have a **matrix** of inputs and a **matrix** of weights now, and we need to perform the **dot product** on them somehow, but how? 

In this example, we need to manage both **matrices** as lists of vectors and perform dot products on all of them in all combinations, resulting in a list of lists of outputs, or a matrix; this operation is called the **matrix product**.

### Matrix Product

[Matrix Product](https://youtu.be/KBPvlUp-m5Y)

The **matrix product** is an operation in which we have **2 matrices**, and we are performing **dot products** of all combinations of **rows from the first matrix** and the **columns of the 2nd matrix**, resulting in a matrix of those atomic dot products.

---

The size of the 2nd dimension of the left matrix must match the size of the 1st dimension of the right matrix. 

<br>

---

![](https://drive.google.com/uc?id=16KvntrAksulJ553YByN6dDEcwyK6Nhqw)

### Transposition for the Matrix Product

**Transposition** simply modifies a matrix in a way that its rows become columns and columns become rows.

![](https://drive.google.com/uc?id=1g__BDqNR2iw2IGrW5hoRZTXtKiIcYofj)

### Behind the scenes

#### row-vector-matrix

A **row-vector-matrix** is a matrix whose first dimension’s size equals 1 and the
second dimension’s size equals `n` - the vector size. 

In [21]:
# Note the double brackets:
np.array([[1, 2, 3]])

array([[1, 2, 3]])

In [25]:
# Or, alternatively:
a = np.array([1, 2, 3])

np.expand_dims(a, axis=0)

array([[1, 2, 3]])

#### column-vector-matrix

A **column-vector-matrix** is a matrix where the 2nd dimension’s size equals 1, in other words, it’s an array of shape `(n, 1)`

In [24]:
np.array([[1, 2, 3]]).T

array([[1],
       [2],
       [3]])

#### Dot product of row-vector-matrix and column-vector-matrix

In [26]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]]).T

np.dot(a, b)

array([[20]])

> We have achieved the same result as the dot product of two vectors, but performed on matrices and returning a matrix.

It’s worth mentioning that NumPy does not have a dedicated method for performing matrix product - the dot product and
matrix product are both implemented in a single method: `np.dot()`

## Final Code

[Animation 1](https://youtu.be/ocrXqFCW3WE)

[Animation 2](https://youtu.be/iBCM3zkHXeo)

In [29]:
inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2.0, 3.0, 0.5]

In [30]:
dot_product = np.dot(
    inputs, 
    np.array(weights).T
)

dot_product

array([[ 2.8  , -1.79 ,  1.885],
       [ 6.9  , -4.81 , -0.3  ],
       [-0.59 , -1.949, -0.474]])

In [32]:
layer_outputs = dot_product + biases

layer_outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

> **Important Note:** 
> 
> The 2nd argument for `np.dot()` is our transposed weights. Previously it was the inputs. 
> 
> As we’ll soon learn, it’s more useful to have a result consisting of a list of layer **outputs per each sample** than **outputs per each neuron**.
>
> We want the resulting array to be sample-related and not neuron-related as we’ll pass those samples further through the network, and the next layer will expect a batch of inputs.